/* eslint-disable */
// Auto-generated from schema/*.schema.json — do not edit by hand.
// Regenerated by site/scripts/gen-types.mjs (runs in prebuild).

// ─── card (from card.schema.json) ─────────────────────────────────

export type CreditCardIndia = {
  [k: string]: unknown;
} & {
  /**
   * Stable slug: <issuer>-<card-slug>. Must match folder/filename.
   */
  id: string;
  /**
   * Official marketed name.
   */
  name: string;
  /**
   * Slug of an entry under data/issuers/.
   */
  issuer: string;
  /**
   * Slug of an entry under data/networks/.
   */
  network: "visa" | "mastercard" | "rupay" | "amex" | "diners";
  /**
   * Network-specific tier (e.g. infinite, signature, world-elite). Must exist in the network's `tiers`.
   */
  network_tier?: string | null;
  /**
   * Market positioning tier.
   */
  tier: "entry" | "mid" | "premium" | "super-premium" | "invite-only";
  /**
   * Credit behaviour. 'charge' means no revolving credit (Amex).
   */
  card_type?: "credit" | "charge" | "secured";
  co_brand?: null | {
    partner: string;
    /**
     * Broad sector of the co-brand partner. Drives filter facets and recommender heuristics — enum expansion needs to coordinate with site/lib code.
     */
    category:
      | "airline"
      | "hotel"
      | "ecommerce"
      | "food-delivery"
      | "quick-commerce"
      | "fuel"
      | "travel-agency"
      | "retail"
      | "telecom"
      | "lifestyle"
      | "railway"
      | "conglomerate"
      | "automotive"
      | "healthcare"
      | "other";
    partner_website?: string;
  };
  status: "active" | "invite-only" | "on-hold" | "discontinued";
  launched_on?: string | null;
  /**
   * Required when status is 'discontinued' (enforced via allOf/if-then below). Nullable otherwise.
   */
  discontinued_on?: string | null;
  /**
   * Optional public URL / site-relative path to a card face image (e.g. /cards/hdfc/infinia.webp). When missing, the site renders a stylised placeholder using the issuer's brand color.
   */
  image_path?: string | null;
  /**
   * @minItems 1
   */
  fees: [FeeRecord, ...FeeRecord[]];
  /**
   * @minItems 1
   */
  rewards: [RewardRecord, ...RewardRecord[]];
  /**
   * @minItems 1
   */
  benefits: [BenefitRecord, ...BenefitRecord[]];
  eligibility: Eligibility;
  application?: {
    apply_url?: string | null;
    pre_approval_check_url?: string | null;
    /**
     * Card id this card is the upgrade of.
     */
    replaces_card?: string | null;
  };
  metadata: Metadata;
};
export type Cycle = "monthly" | "quarterly" | "annual" | "statement" | "per-txn";
/**
 * At least one of visits_per_cycle or spend_threshold_inr must be present — an empty {} or a lounge entry with neither produces a ghost 'lounge access ✓' badge with no real benefit.
 */
export type LoungeDetails = LoungeDetails1 & {
  visits_per_cycle?: number | "unlimited";
  cycle?: Cycle;
  guests_per_visit?: number | "unlimited";
  via?: (
    | "visa"
    | "mastercard"
    | "rupay"
    | "amex"
    | "diners"
    | "priority-pass"
    | "dreamfolks"
    | "dragonpass"
    | "loungekey"
    | "issuer-direct"
  )[];
  /**
   * Prior-cycle spend required to unlock complimentary visits (common on Axis/HDFC post-2024).
   */
  spend_threshold_inr?: number | null;
  spend_threshold_cycle?: Cycle;
  notes?: string;
} & LoungeDetails1 & {
    visits_per_cycle?: number | "unlimited";
    cycle?: Cycle;
    guests_per_visit?: number | "unlimited";
    via?: (
      | "visa"
      | "mastercard"
      | "rupay"
      | "amex"
      | "diners"
      | "priority-pass"
      | "dreamfolks"
      | "dragonpass"
      | "loungekey"
      | "issuer-direct"
    )[];
    /**
     * Prior-cycle spend required to unlock complimentary visits (common on Axis/HDFC post-2024).
     */
    spend_threshold_inr?: number | null;
    spend_threshold_cycle?: Cycle;
    notes?: string;
  };
export type LoungeDetails1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

export interface FeeRecord {
  effective_from: string;
  effective_until: string | null;
  joining_fee_inr: number;
  annual_fee_inr: number;
  /**
   * If different from annual_fee_inr (rare).
   */
  renewal_fee_inr?: number | null;
  fee_waiver?: null | {
    spend_inr: number;
    cycle: Cycle;
    conditions?: string;
  };
  forex_markup_pct?: number | null;
  finance_charge_monthly_pct?: number | null;
  cash_advance_fee?: null | {
    pct?: number;
    min_inr?: number;
  };
  late_payment_slabs?:
    | {
        up_to_inr: number | "any";
        fee_inr: number;
      }[]
    | null;
  overlimit_fee?: null | {
    pct?: number;
    min_inr?: number;
    max_inr?: number;
  };
  gst_applicable?: boolean;
  emi_conversion?: null | {
    interest_pct_annual?: number | null;
    processing_fee_pct?: number | null;
    processing_fee_min_inr?: number | null;
    notes?: string;
  };
  balance_transfer?: null | {
    interest_pct?: number | null;
    processing_fee_pct?: number | null;
    processing_fee_min_inr?: number | null;
    tenure_months?: number | null;
    notes?: string;
  };
  /**
   * Flat fee per international ATM withdrawal (separate from cash_advance_fee on domestic ATMs).
   */
  foreign_atm_inr?: number | null;
  /**
   * Annual fee for an additional / family / add-on card. Often free.
   */
  supplementary_card_fee_inr?: number | null;
  source: Source;
  notes?: string;
}
export interface Source {
  url: string;
  retrieved_on: string;
  notes?: string;
}
export interface RewardRecord {
  effective_from: string;
  effective_until: string | null;
  currency: "points" | "cashback" | "miles";
  /**
   * e.g. 'Reward Points', 'EDGE Miles', 'Membership Rewards'.
   */
  currency_name?: string | null;
  /**
   * Slug of an entry under data/loyalty_programs/. When set, the card's reward currency is the program's currency, and stacking accelerators may credit program baseline/tier/channel earn on top of the card's slice.
   */
  loyalty_program?: string | null;
  base: {
    rate: number;
    per_inr: number;
    /**
     * Best-case (face) INR value of one unit on redemption. When loyalty_program is set, prefer the program's unit_value_inr.realized for math.
     */
    unit_value_inr?: number | null;
    /**
     * Conservative realized INR value of one unit. Calculator math prefers this when present.
     */
    unit_value_inr_realized?: number | null;
  };
  accelerated?: (
    | {
        [k: string]: unknown;
      }
    | {
        [k: string]: unknown;
      }
  )[];
  /**
   * Categories earning zero rewards.
   */
  exclusions?: (
    | "fuel"
    | "wallet-loads"
    | "rent"
    | "government"
    | "utilities"
    | "insurance-premiums"
    | "education"
    | "jewellery"
    | "emi"
    | "cash-advance"
    | "gift-cards"
    | "mutual-funds"
    | "crypto"
    | "other"
  )[];
  /**
   * Freeform caps not modellable above (e.g. monthly combined cap).
   */
  capping_rules?: string[];
  /**
   * Conservative/typical INR value per unit across practical redemptions.
   */
  redemption_floor_value_inr?: number | null;
  /**
   * Best-case achievable INR value per unit on high-value redemptions.
   */
  redemption_ceiling_value_inr?: number | null;
  redemption?: {
    type:
      | "statement-credit"
      | "catalog"
      | "airmiles"
      | "hotel-points"
      | "voucher"
      | "cashback-bank"
      | "product"
      | "other";
    program?: string;
    rate_inr_per_unit?: number | null;
    /**
     * e.g. '2:1' (points:miles).
     */
    ratio?: string | null;
    min_units?: number | null;
    fee_inr?: number | null;
    constraints?: string;
    transfer_partners?: {
      partner_name: string;
      partner_type: "airline" | "hotel" | "bank-loyalty" | "voucher-marketplace";
      /**
       * e.g. '5:2' (source:target).
       */
      transfer_ratio?: string | null;
      min_transfer_units?: number | null;
      transfer_block_units?: number | null;
      transfer_fee_inr?: number | null;
      expected_transfer_time?: string | null;
      last_verified_on?: string | null;
      notes?: string;
    }[];
  }[];
  /**
   * External loyalty programs the card's points can be transferred to (e.g. Marriott Bonvoy, Accor Live Limitless, Air India Maharajah Club, KrisFlyer).
   */
  transfer_partners?: {
    program: string;
    category?: "airline" | "hotel" | "other";
    /**
     * Conversion ratio expressed as 'X:Y' where X = source points and Y = partner units. e.g. '2:1'.
     */
    ratio?: string | null;
    min_transfer?: number | null;
    fee_inr?: number | null;
    notes?: string;
  }[];
  source: Source;
  notes?: string;
}
export interface BenefitRecord {
  effective_from: string;
  effective_until: string | null;
  lounge_access?: {
    domestic?: LoungeDetails;
    international?: LoungeDetails;
  } | null;
  golf?: {
    rounds_per_cycle?: number | "unlimited";
    lessons_per_cycle?: number | "unlimited";
    cycle?: Cycle;
    notes?: string;
  } | null;
  milestones?: {
    spend_inr: number;
    cycle: Cycle;
    benefit: string;
    value_inr?: number | null;
    reward_kind?: "points" | "miles" | "cashback" | "voucher" | "fee-waiver" | "other";
    reward_units?: number | null;
    reward_currency_name?: string | null;
    trigger_window?: "first-year" | "anniversary-year" | "rolling" | "one-time";
    is_repeatable?: boolean | null;
    max_awards_per_cycle?: number | null;
    redemption_constraint_ref?: string | null;
  }[];
  welcome?: {
    condition?: string;
    benefit: string;
    value_inr?: number | null;
    window_days?: number | null;
  }[];
  insurance?: {
    type:
      | "air-accident"
      | "personal-accident"
      | "lost-card-liability"
      | "purchase-protection"
      | "travel-medical"
      | "trip-delay"
      | "baggage-loss"
      | "credit-shield"
      | "fraud-liability"
      | "other";
    sum_insured_inr: number;
    conditions?: string;
  }[];
  fuel_surcharge_waiver?: {
    pct: number;
    min_txn_inr?: number | null;
    max_txn_inr?: number | null;
    cap_per_cycle_inr?: number | null;
    cycle?: Cycle;
    notes?: string;
  } | null;
  dining?: {
    program?: string;
    discount_pct?: number | null;
    notes?: string;
  } | null;
  movies?: {
    type?: "bogo" | "discount" | "free";
    partner?: string;
    max_per_cycle?: number | null;
    cycle?: Cycle;
    cap_inr?: number | null;
    notes?: string;
  } | null;
  concierge?: boolean;
  /**
   * Surcharge waivers other than fuel (e.g. railway booking, utility bill, online education). Fuel has its own dedicated `fuel_surcharge_waiver` field.
   */
  surcharge_waivers?: {
    category: "railway" | "utilities" | "telecom" | "education" | "online" | "wallet-loads" | "rent" | "other";
    pct: number;
    min_txn_inr?: number | null;
    max_txn_inr?: number | null;
    cap_per_cycle_inr?: number | null;
    cycle?: Cycle;
    notes?: string;
  }[];
  /**
   * Anything that doesn't fit above (e.g. free OTT subscription).
   */
  other?: {
    name: string;
    description: string;
    value_inr?: number | null;
  }[];
  source: Source;
  notes?: string;
}
export interface Eligibility {
  min_age?: number | null;
  max_age?: number | null;
  income_inr_annual?: {
    salaried?: number | null;
    self_employed?: number | null;
  };
  credit_score_min?: number | null;
  residency?: "resident-indian" | "nri" | "either";
  notes?: string;
}
export interface Metadata {
  last_verified_on: string;
  /**
   * Date of the last bulk/automated freshness sweep. Distinct from last_verified_on, which may only move when a human/agent actually compared the record's fields against the cited sources.
   */
  last_swept_on?: string | null;
  tags?: string[];
}

// ─── issuer (from issuer.schema.json) ─────────────────────────────────

export interface CardIssuer {
  /**
   * Lowercase slug. Must match the filename and be used as the `issuer` key on cards.
   */
  id: string;
  /**
   * Common name used in UI, e.g. 'HDFC Bank'.
   */
  name: string;
  /**
   * Optional shorthand, e.g. 'HDFC'.
   */
  short_name?: string;
  /**
   * Registered legal name, e.g. 'HDFC Bank Limited'.
   */
  legal_name: string;
  website: string;
  customer_care?: {
    phone?: string;
    email?: string;
  };
  /**
   * Broad issuer category.
   */
  type?: "bank" | "small-finance-bank" | "nbfc" | "fintech" | "foreign-bank" | "charge-card-company";
  /**
   * Public URL or site-relative path to the issuer's logo (e.g. /logos/issuers/hdfc.svg). When present, the site renders the logo in place of the short/long name text.
   */
  logo_path?: string | null;
  /**
   * Issuer's primary brand color as a #RRGGBB hex string. Used as the background for the card-image placeholder tile when a card has no real card-face image.
   */
  brand_color?: string | null;
  notes?: string;
}

// ─── network (from network.schema.json) ─────────────────────────────────

export interface CardNetwork {
  /**
   * Lowercase slug. Must match the filename.
   */
  id: string;
  name: string;
  /**
   * Valid tier slugs for this network (e.g. infinite, signature, world, world-elite, platinum).
   *
   * @minItems 1
   */
  tiers: [string, ...string[]];
  website?: string;
  /**
   * Public URL or site-relative path to the network's logo (e.g. /logos/networks/visa.svg). When present, the site renders the logo in place of the text label.
   */
  logo_path?: string | null;
  notes?: string;
}

// ─── loyalty_program (from loyalty_program.schema.json) ─────────────────────────────────

export interface LoyaltyProgramThirdPartyJoinedToCardsById {
  /**
   * Stable slug. Must match filename. Cards reference this via rewards[].loyalty_program.
   */
  id: string;
  name: string;
  type: "airline" | "hotel" | "retail" | "transit" | "other";
  partner?: string;
  /**
   * Case-insensitive substring tokens that, if present in a card's `co_brand.partner`, mean the card should reference this programme via `rewards[].loyalty_program`. Used by the validator to flag missing loyalty links on co-brand cards.
   *
   * @minItems 1
   */
  co_brand_partner_aliases?: [string, ...string[]];
  currency: "points" | "miles" | "cashback";
  currency_name?: string | null;
  unit_value_inr: {
    /**
     * Marketing/face redemption value of one unit (e.g. 1 BluChip = ₹1 on IndiGo bookings).
     */
    face: number;
    /**
     * Observed effective value after fare inflation, blackouts, redemption friction. Single scalar; usually midpoint of an observed range. Calculator math uses this number.
     */
    realized: number;
    realized_source?: {
      method?: "midpoint" | "low" | "observed-redemption" | "survey";
      /**
       * @minItems 2
       * @maxItems 2
       */
      range?: [number, number];
      notes?: string;
      references?: {
        url: string;
        retrieved_on: string;
        notes?: string;
      }[];
    } | null;
  };
  earn?: {
    baseline?: {
      rate: number;
      per_inr: number;
      notes?: string;
    } | null;
    channels?: {
      channel:
        | "issuer-portal"
        | "cobrand-merchant"
        | "third-party-ota"
        | "merchant-app"
        | "merchant-web"
        | "physical"
        | "online-any";
      /**
       * @minItems 1
       */
      merchants: [string, ...string[]];
      rate: number;
      per_inr: number;
      notes?: string;
    }[];
    tiers?: {
      id: string;
      name?: string;
      requirements?: string;
      bonus_rate: number;
      bonus_per_inr: number;
      notes?: string;
    }[];
  };
  redemption_paths?: {
    type: "voucher" | "airmiles" | "hotel-points" | "statement-credit" | "cashback-bank" | "transfer" | "other";
    program?: string;
    rate_inr_per_unit?: {
      face?: number;
      realized?: number;
    } | null;
    constraints?: string;
    notes?: string;
  }[];
  metadata: {
    last_verified_on: string;
    source?: {
      url: string;
      retrieved_on: string;
      notes?: string;
    };
    notes?: string;
  };
}

